# Enables debug messages to be shown in console
Debug: false
# How far away a normal roll is broadcasted
MessageRadius: 30
# If players should be nicknamed as their character
NicknamePlayers: true
# Maximum amount of dice rolled at once in a global or local roll
PublicDiceLimit: 15
# Maximum amount of dice rolled at once in a private roll
PrivateDiceLimit: 40
# Maximum dice sides in a roll
DiceSidesLimit: 99
# If mobs should drop exp upon death
PreventMobsDroppingExp: true
# If players should be prevented from crafting diamond armor
PreventCraftingDiamondArmor: true
colors:
  primary: YELLOW
  secondary: GRAY
  highlights: RED